# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6013da42b80e33257d512ba97a0220f8da9e8ba39733fe650ac4e14257a49aba084cb186aba183e7de6bb3ad20bf0949637078f95b14922acd3303a573e48b

test:
  secret_key_base: 70d315a1473b3122de70eb132e597194597a1689843cbaf52503d639a3a1928475e974aeea7b73b50694aa02be84c0f46923066615cca50f3356398e64b17cee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
